# Generated by Django 4.2.3 on 2023-08-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20230731_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Birthday', 'Birthday'), ('Work Anniversary', 'Work Anniversary'), ('Other', 'Other')], max_length=200, verbose_name='Event Title')),
                ('eventDate', models.DateField()),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Event Details',
            },
        ),
    ]
