# Generated by Django 4.2.3 on 2023-08-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_eventdetails_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='wishes',
            field=models.TextField(blank=True, default='No Events', null=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='event_type',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Work Anniversary', 'Work Anniversary'), ('No Events', 'No Events')], max_length=200, verbose_name='Event Type'),
        ),
    ]
